spring :
  application :
    name : chat-app
  datasource:
    url: jdbc:mysql://localhost:3306/chat_app
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update